# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-alpine AS builder
WORKDIR /app

# Copy project files
COPY package.json tsconfig.json ./
COPY src ./src

# Install dependencies and build
RUN npm install --ignore-scripts
RUN npm run build

# Final runtime image
FROM node:lts-alpine
WORKDIR /app

# Copy build output and dependencies
COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules

ENV NODE_ENV=production

CMD ["node", "build/index.js"]
